### ISSUE TITLE
background noise not set when performing the modeling

### ISSUE THREAD

**Issue by sibirrer** [ClarkGuilty/rung0_lenstronomy#1]
Hi Javier,
I was just glancing through your notebooks and noticed that when you re-set the kwargs_data object, you did not pass the background noise level and it got automatically set =1 (which is way too high relative to what is present in your data). I will make an update in lenstronomy that gives a raise statement when you don't set this property yourself in the simulation_util function. Just wanted to let you know.

Best,
Simon

**Comment by ClarkGuilty** [comment]
Hello Simon,
Thanks a lot. I made the pertinent corrections.

Best regards,
Javier
